# Generated by Django 4.1 on 2023-05-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='images/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
