# Generated by Django 4.1 on 2023-05-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Ник')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('isactive', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Сообщения на стене',
                'verbose_name_plural': 'Сообщения на стене',
                'ordering': ['-time_created', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='MyPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('posttext', models.TextField(blank=True, verbose_name='Текст')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('postimage', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('isactive', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Мои посты',
                'verbose_name_plural': 'Мои посты',
                'ordering': ['-time_created', 'title'],
            },
        ),
    ]
