# Generated by Django 4.1 on 2023-05-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_boardmessages_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('posttext', models.TextField(blank=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('postimage', models.ImageField(upload_to='images/', verbose_name='image')),
            ],
        ),
    ]
