# Generated by Django 4.1 on 2023-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmessages',
            options={'ordering': ['-time_created', 'nickname'], 'verbose_name': 'Сообщения на стене', 'verbose_name_plural': 'Сообщения на стене'},
        ),
        migrations.AlterModelOptions(
            name='myposts',
            options={'ordering': ['-time_created', 'title'], 'verbose_name': 'Мои посты', 'verbose_name_plural': 'Мои посты'},
        ),
        migrations.AlterField(
            model_name='boardmessages',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='boardmessages',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='boardmessages',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='boardmessages',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='myposts',
            name='postimage',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='myposts',
            name='posttext',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='myposts',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='myposts',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
