# Generated by Django 4.1 on 2023-05-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_boardmessages_options_alter_myposts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myposts',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
